### ISSUE TITLE
XCode error: AzureCore contains mixed language source files; feature not supported

### ISSUE THREAD

**Issue by nherzalla2020** [Azure/azure-sdk-for-ios#476] opened 2020-10-06 21:19 UTC
I tried to import the library in Xcode I received the attached image error
<img width="808" alt="Screen Shot 2020-10-06 at 5 12 19 PM" src="https://user-images.githubusercontent.com/72473174/95261222-05788380-07f8-11eb-9af6-bdeb66c144c1.png">

**Comment by bsiegel** [comment] 2020-10-07 20:49
Hi @nherzalla2020, thank you for the bug report. We have seen this issue with Xcode 11.4 - there is a regression in the version of Swift that shipped with the Xcode 11.4 series, can you please let us know what version of Xcode you're using? If you are using 11.4, updating to Xcode 11.5 or higher should resolve the issue.

**Comment by nherzalla2020** [comment] 2020-10-07 21:41
I'm using Xcode 12.0.1 see the attached.
<img width="1130" alt="Screen Shot 2020-10-07 at 5 39 20 PM" src="https://user-images.githubusercontent.com/72473174/95391034-4dfd7300-08c4-11eb-8f63-d9329114cc54.png">

**Comment by bsiegel** [comment] 2020-10-08 23:20
Thanks for confirming your Xcode version - we haven't encountered this issue with Xcode 12 so far, we'll investigate. Can you please confirm what version rule you used when adding the SDK to your project?

**Comment by nherzalla2020** [comment] 2020-10-09 00:16
The latest
<img width="734" alt="Screen Shot 2020-10-08 at 8 15 35 PM" src="https://user-images.githubusercontent.com/72473174/95527385-25987600-09a3-11eb-8588-d776fe99af0d.png">
 it says 0.5.0 as the attached image

**Comment by bsiegel** [comment] 2020-10-12 22:17
@nherzalla2020 Can you please try setting the version specifier to "Version: Up to next major: 1.0.0-beta.2" and let us know if you are still experiencing the issue? Versions below 1.0 are deprecated, the SDK has been re-written since then and the new SDK starts at version 1.

**Comment by nherzalla2020** [comment] 2020-10-12 22:59
That worked 👍 thank you for the help

**Comment by bsiegel** [comment] 2020-10-13 00:42
Glad to hear, closing the issue.

**Closed by bsiegel** 2020-10-13 00:42 UTC
