### ISSUE TITLE
[BUG] totalParticipantCount changes to 1 if another incoming call arrives

### ISSUE THREAD

**Issue by JasonWeinzierl** [Azure/azure-sdk-for-ios#1715] opened 2024-02-28 20:03 UTC
**Describe the bug**

If I'm in a call with another participant (totalParticipantCount=2), and a third user calls me, then total participant count changes to 1.

***Exception or Stack Trace***

N/A

**To Reproduce**

1. Start a call with another participant.
2. Receive an incoming call from a third participant.
3. totalParticipantCount of your active call will change to 1.

***Code Snippet***

```swift
extension MyCallDelegate: CallDelegate {
  func call(_ call: Call, didChangeTotalParticipantCount args: PropertyChangedEventArgs) {
    // call.totalParticipantCount will be 1 here when incoming call arrives.
  }
}
```

**Expected behavior**

totalParticipantCount of my active call should not change if my active call is still Connected.

**Screenshots**

N/A

**Setup (please complete the following information):**

- OS: iOS: 17.3
- IDE: Xcode: 15.2
- Version of the Library used: AzureCommunicationCalling: 2.9.0-beta.1

**Additional context**

This seems to be occurring on the Android library too.  Is this intentional behavior, and if so, why and how do we restore totalParticipantCount back to 2 if the incoming call has been rejected?

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by tjprescott** [comment] 2024-02-28 20:33
@raosanat can you take a look?

**Comment by lucianopa-msft** [comment] 2024-03-05 19:44
Hi @JasonWeinzierl,
When you receive the event value if you log the `call?.id` is that for the same call object then previous log? 
Another few questions is if the incoming call was accepted or we are still in ringing mode when the event with `1` participant arrived.

**Comment by JasonWeinzierl** [comment] 2024-03-05 20:03
when logging each event as it happens, this is what i see (comments added):

```
// milliseconds before the incoming call arrives, totalParticipantCount drops to 1
13:48:07.610284-0600	"[ACS Calling] Call 1786799b-09f1-4663-bbf7-b513a642f88d total participant count changed: 1"

// these events also get emitted for my active call
13:48:07.612117-0600	"[ACS Calling] Call 1786799b-09f1-4663-bbf7-b513a642f88d role changed: Uninitialized"
13:48:07.612154-0600	"[ACS Calling] Call 1786799b-09f1-4663-bbf7-b513a642f88d isMuted changed: true"

// the incoming call arrives
13:48:07.626130-0600	"[ACS Calling] Call agent: incoming call 3d032881-3cc7-494f-85e9-8f745abc9299 from {\"displayName\":\"<snip>\",\"identifier\":{\"rawId\":\"<snip>\",\"communicationUserId\":\"<snip>\",\"kind\":\"communicationUser\"}}. Video enabled: true"

// the active call's state emits the same value of Connected
13:48:07.671869-0600	"[ACS Calling] Call 1786799b-09f1-4663-bbf7-b513a642f88d state changed from Connected to Connected with 1 remote participants (1 remote video streams) and 1 local video streams"

// the other participant in my active call's state also emits a duplicate value
13:48:07.671956-0600	"[ACS Calling] Remote participant <snip> state changed: Connected"

// my code rejects the incoming call immediately
13:48:07.899265-0600	"[ACS Calling] Incoming call 3d032881-3cc7-494f-85e9-8f745abc9299 rejected."

// my local video stream turns itself off for some reason.  possibly related?  this doesn't happen on Android.
13:48:07.900513-0600	"[ACS Calling] Local video stream 0F3B7F9D-BA91-4124-AB48-9FEBB48AE327 state changed from Started to Stopping with message ''."
13:48:07.901365-0600	"[ACS Calling] Local video stream 0F3B7F9D-BA91-4124-AB48-9FEBB48AE327 state changed from Stopping to Stopped with message ''."

// my active call again reminds me it's connected
13:48:07.903597-0600	"[ACS Calling] Call 1786799b-09f1-4663-bbf7-b513a642f88d state changed from Connected to Connected with 1 remote participants (1 remote video streams) and 0 local video streams"

// the remote participant again reminds me they're connected
13:48:07.903631-0600	"[ACS Calling] Remote participant <snip> state changed: Connected"

// the incoming call's "ended" event fires.
13:48:07.903666-0600	"[ACS Calling] Incoming call 3d032881-3cc7-494f-85e9-8f745abc9299 ended: {\"code\":603,\"subCode\":0}"
```

if i log totalParticipantCount after this sequence of events, it is still `1`.

This doesn't happen to me using the Android calling library's latest version 2.6.0-beta.8.

**Comment by lucianopa-msft** [comment] 2024-03-05 20:36
Ok, thank you for the logs, we will try repro and get back with updates as soon as possible.

**Comment by lucianopa-msft** [comment] 2024-03-05 22:38
I couldn't reproduce this on our side, can you send a set of logs with all `total participant count changed` logs, I only see one entry(the one after incoming call), but from what I understand after connecting in the first call the total participant count is correct right?

**Comment by JasonWeinzierl** [comment] 2024-03-05 23:19
yes, the total participant count is initially correct.  it's only wrong after the incoming call.

here's a more comprehensive example. 

```js
// We ("user 1") create a local video stream and then call user 2.
16:52:31.082156-0600	"[ACS Calling] Constructed LocalVideoStream A0EA7F95-84C1-4642-8A34-87D2A16F275F with source com.apple.avfoundation.avcapturedevice.built-in_video:1 (UsbCamera)."

// Call agent didUpdateCalls event fires.
16:52:31.206748-0600	"[ACS Calling] Call agent 849f100a-1c6a-4185-a393-f45cad12ed93 calls updated: 1 added, 0 removed."

// We set up delegates to listen to the various events of the call, its participants, call diagnostics feature, dominant speakers, etc.
16:52:31.224490-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 isMuted changed: true"
16:52:31.228415-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 state changed from None to Connecting."
16:52:33.120287-0600	"[ACS Calling] Participant <snip user 2 id> state changed: Ringing"
16:52:33.133908-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 state changed from Connecting to Ringing."

// user 2 accepts our call. The call starts up.
16:52:35.385168-0600	"[ACS Calling] Participant <snip user 2 id> state changed: Connected"
16:52:35.385236-0600	"[ACS Calling] Participant <snip user 2 id> isMuted changed: false"
16:52:35.385452-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 isMuted changed: true"
16:52:35.394567-0600	"[ACS Calling] Participant <snip user 2 id> added video stream 133 (id 133) of type Video in state Available."
16:52:35.475080-0600	"[ACS Calling] Local video stream A0EA7F95-84C1-4642-8A34-87D2A16F275F state changed from Available to Started with message ''."
16:52:35.475254-0600	"[ACS Calling] Remote video stream 133 (id 133) state changed from Available to Started."
16:52:35.482342-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 state changed from Ringing to Connected with 1 remote participants (1 remote video streams) and 1 local video streams"
16:52:35.482378-0600	"[ACS Calling] Participant <snip user 2 id> state changed: Connected"
16:52:36.062781-0600	"[ACS Calling] Participant <snip user 2 id> isMuted changed: true"
16:52:36.064059-0600	"[ACS Calling] Participant <snip user 2 id> display name changed: <snip user 2>"
// NOTE: total participant count correctly emits 2.
16:52:36.064650-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 total participant count changed: 2"
16:52:36.068717-0600	"[ACS Calling] Remote video stream 133 (id 133) state changed from Stopping to Stopped."
16:52:36.068891-0600	"[ACS Calling] Remote video stream 133 (id 133) state changed from Stopped to Available."
16:52:36.096474-0600	"[ACS Calling] Remote video stream 133 (id 133) state changed from Available to Started."
16:52:36.100208-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 network diagnostic 'networkReconnect' changed: Good"
16:52:36.152484-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 isMuted changed: false"

// some testing.  user 2 toggles their video on and off.
16:52:45.688080-0600	"[ACS Calling] Remote video stream 133 (id 133) state changed from Started to Stopping."
16:52:45.692317-0600	"[ACS Calling] Remote video stream 133 (id 133) state changed from Stopping to Stopped."
16:52:45.692481-0600	"[ACS Calling] Remote video stream 133 (id 133) state changed from Stopped to NotAvailable."
16:52:45.692539-0600	"[ACS Calling] Participant <snip user 2 id> removed video stream 133 (id 133)."
16:52:45.694308-0600	"[ACS Calling] Participant <snip user 2 id> added video stream 136 (id 136) of type Video in state Available."
16:52:45.760843-0600	"[ACS Calling] Remote video stream 136 (id 136) state changed from Available to Started."
16:52:48.933573-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 dominant speakers count changed from 0 to 0 at 2024-03-05T22:52:48.000Z."

// user 2 adds user 3 to the current call.
16:52:51.095763-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 participants updated: 1 added, 0 removed."
16:52:51.095798-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 added participant <snip user 3 id> with display name '<snip user 3>' in state Connected."
// NOTE: total participant count correctly emits 3.
16:52:51.095834-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 total participant count changed: 3"
16:52:52.092689-0600	"[ACS Calling] Participant <snip user 3 id> isMuted changed: true"
16:52:54.971075-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 dominant speakers count changed from 0 to 0 at 2024-03-05T22:52:54.000Z."

// user 3 leaves the current call.
16:52:59.246593-0600	"[ACS Calling] Participant <snip user 3 id> state changed: Disconnected"
16:52:59.246709-0600	"[ACS Calling] Remote video stream 138 (id 138) state changed from Available to Stopped."
16:52:59.247009-0600	"[ACS Calling] Remote video stream 138 (id 138) state changed from Stopped to NotAvailable."
16:52:59.247426-0600	"[ACS Calling] Participant <snip user 3 id> removed video stream 138 (id 138)."
16:52:59.247569-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 dominant speakers count changed from 0 to 0 at 2024-03-05T22:52:59.000Z."
16:52:59.248023-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 participants updated: 0 added, 1 removed."
16:52:59.248208-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 removed participant <snip user 3 id>."
// NOTE: total participant count correctly emits 2.
16:52:59.248349-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 total participant count changed: 2"

// user 3 calls us directly.
// NOTE: BUG: total participant count changes to 1 here.
16:53:11.947211-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 total participant count changed: 1"
// role and isMuted re-emit their values for unknown reason.
16:53:11.947244-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 role changed: Uninitialized"
16:53:11.949455-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 isMuted changed: false"
// Call re-emits Connected for unknown reason.
16:53:11.951173-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 state changed from Connected to Connected with 1 remote participants (1 remote video streams) and 1 local video streams"
// user 2 re-emits Connected for unknown reason. 
16:53:11.951214-0600	"[ACS Calling] Participant <snip user 2 id> state changed: Connected"
16:53:11.965060-0600	"[ACS Calling] Incoming call fb6a09e1-5379-4872-ab6a-edb9f225f9e3 from {\"displayName\":\"<snip user 3>\",\"identifier\":{\"rawId\":\"<snip user 3 id>\",\"communicationUserId\":\"<snip user 3 id>\",\"kind\":\"communicationUser\"}}. Video enabled: true"

// We reject user 3's incoming call.
// Our local video stream turns off for unknown reason.
16:53:12.663886-0600	"[ACS Calling] Local video stream A0EA7F95-84C1-4642-8A34-87D2A16F275F state changed from Started to Stopping with message ''."
16:53:12.664119-0600	"[ACS Calling] Local video stream A0EA7F95-84C1-4642-8A34-87D2A16F275F state changed from Stopping to Stopped with message ''."
// Call re-emits Connected for unknown reason.
16:53:12.664964-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 state changed from Connected to Connected with 1 remote participants (1 remote video streams) and 0 local video streams"
// user 2 re-emits Connected for unknown reason. 
16:53:12.664999-0600	"[ACS Calling] Participant <snip user 2 id> state changed: Connected"
16:53:12.665508-0600	"[ACS Calling] Incoming call fb6a09e1-5379-4872-ab6a-edb9f225f9e3 ended: {\"code\":603,\"subCode\":0}"
16:53:12.666362-0600	"[ACS Calling] Incoming call fb6a09e1-5379-4872-ab6a-edb9f225f9e3 rejected."

// user 2 again adds user 3 to our current call.
16:53:27.468163-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 participants updated: 1 added, 0 removed."
16:53:27.468267-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 added participant <snip user 3 id> with display name '<snip user 3>' in state Connected."
// NOTE: total participant count correctly emits 3.
16:53:27.469487-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 total participant count changed: 3"
16:53:28.512768-0600	"[ACS Calling] Participant <snip user 3 id> isMuted changed: true"
// user 3 leaves again.
16:53:41.248931-0600	"[ACS Calling] Participant <snip user 3 id> state changed: Disconnected"
16:53:41.249032-0600	"[ACS Calling] Remote video stream 142 (id 142) state changed from Available to NotAvailable."
16:53:41.249105-0600	"[ACS Calling] Participant <snip user 3 id> removed video stream 142 (id 142)."
16:53:41.249722-0600	"[ACS Calling] Participant <snip user 3 id> added video stream 142 (id -1) of type Video in state NotAvailable."
16:53:41.249806-0600	"[ACS Calling] Participant <snip user 3 id> removed video stream 142 (id -1)."
16:53:41.249893-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 dominant speakers count changed from 0 to 0 at 2024-03-05T22:53:41.000Z."
16:53:41.250766-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 participants updated: 0 added, 1 removed."
16:53:41.250986-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 removed participant <snip user 3 id>."
// NOTE: total participant count correctly drops to 2.
16:53:41.251135-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 total participant count changed: 2"

// We end the call.
16:53:50.046168-0600	"[ACS Calling] Call bf691200-9624-49e9-b5d0-f6e45dea8e10 state changed from Connected to Disconnected with reason {\"code\":0,\"subCode\":0}"
16:53:50.071489-0600	"[ACS Calling] Call agent 849f100a-1c6a-4185-a393-f45cad12ed93 calls updated: 0 added, 1 removed."
```

**Comment by lucianopa-msft** [comment] 2024-03-06 14:45
Hi @JasonWeinzierl 
Are you using call kit from SDK or implementing CallKit in your own application?
Also, can you provide (even if is in pseudo code) the operations you are doing in the code that receives the incoming call (callkit code to report incoming call as well if you are implementing on your own)?

**Comment by JasonWeinzierl** [comment] 2024-03-06 17:20
Yes we are using SDK CallKit.

We are using the SDK via React Native, so I can't post the entire code here, but here's some relevant bits:

We pass in an object from React Native as an NSDictionary and parse it into the provider configuration:

```swift
extension NSDictionary {
  private func getCXProviderConfiguration() -> CXProviderConfiguration {
    let providerConfiguration: CXProviderConfiguration
    if #available(iOS 14, *) {
      providerConfiguration = CXProviderConfiguration()
    } else {
      providerConfiguration = CXProviderConfiguration(localizedName: "my-app-calling")
    }

    providerConfiguration.supportsVideo = true
    providerConfiguration.supportedHandleTypes = [.generic, .phoneNumber]
    providerConfiguration.maximumCallGroups = 1
    providerConfiguration.maximumCallsPerCallGroup = 1

    if let imageName = self["imageName"] as? String,
       let iconImage = UIImage(named: imageName) {
      providerConfiguration.iconTemplateImageData = iconImage.pngData()
    }
    if let ringtoneSound = self["ringtoneSound"] as? String {
      providerConfiguration.ringtoneSound = ringtoneSound
    }
    if let includeCallsInRecents = self["includeCallsInRecents"] as? Bool {
      providerConfiguration.includesCallsInRecents = includeCallsInRecents
    }
    return providerConfiguration
  }
}
```

We use that provider configuration to create `CallKitOptions`.

Other relevant info: we're populating `CallKitOptions.provideRemoteInfo` with a callback to look up info for the incoming caller.  Since that function needs to be synchronous, it might be taking a long time to return the remote info, so perhaps that could be blocking/conflicting with incoming call behavior?  (It would be nice if `provideRemoteInfo` could be asynchronous.)

Then we create the call agent.  We set up a delegate to listen for events kinda like this:

```swift
let callAgent = try await callClient.createCallAgent(userCredential: credential, options: callAgentOptions)
let adapter = AcsCallAgentAdapter(callAgent)
callAgent.delegate = adapter
// and we keep a strong reference to the adapter for ARC.
```

Our delegate implementation looks kinda like this:

```swift
class AcsCallAgentAdapter: NSObject, CallAgentDelegate {
  func callAgent(_ callAgent: CallAgent, didRecieveIncomingCall incomingCall: IncomingCall) {
    // set up delegate and emit to React Native
  }

  func callAgent(_ callAgent: CallAgent, didUpdateCalls args: CallsUpdatedEventArgs) {
    // set up delegates and emit to React Native for each added/removed call
  }
}
```

When we receive an incoming call, we set up a delegate just like we did for the call agent.  We also emit all events up to React Native so we can modify the UI accordingly.  We set up delegates as new calls are emitted too, and emit those events to React Native too.

The call delegate looks something like this:

```swift
class AcsCallAdapter: NSObject, CallDelegate {
  func call(_ call: Call, didChangeTotalParticipantCount args: PropertyChangedEventArgs) {
    // emit to React Native
  }
}
```

When totalParticipantCount changes, we emit it to React Native and that's where the previous logs I posted come from.  However, I've added `os_log` logs here in the Swift code, and it still doesn't log expected values, so I don't think anything's getting lost when sending it to React Native.

As mentioned in the issue description, this is on 2.9.0-beta.1; we previously weren't having this problem on 2.8.0-beta.3.

Thanks for your quick answers so far, I appreciate the support.

**Comment by lucianopa-msft** [comment] 2024-03-06 18:27
I am not able to reproduce the bug, but trying on top of our master branch, so it is possible that issue is a regression that has been fixed. But I will verify the same version as well.

**Comment by lucianopa-msft** [comment] 2024-03-06 20:08
It looks like 2.9.0-beta.1 it is reproducible, but master is not, so fix will be available in next released beta.

**Comment by lucianopa-msft** [comment] 2024-04-18 13:00
@JasonWeinzierl Can you verify that with 2.10 and close this issue if that is fixed?

**Closed** 2024-08-12 18:11 UTC
Labels: question, Communication, customer-reported
