### ISSUE TITLE
[BUG] IsSpeakingWhileMicrophoneIsMuted not working when starting the call muted

### ISSUE THREAD

**Issue by alexvolchek** [Azure/azure-sdk-for-ios#1700] opened 2024-02-12 13:26 UTC
**Describe the bug**
Method `mediaDiagnostics(_: MediaDiagnostics, didChangeIsSpeakingWhileMicrophoneIsMuted args: DiagnosticFlagChangedEventArgs)` of `ACSMediaDiagnosticsDelegate` is not called immediately after starting the call muted. Only after unmuting and muting again.

**To Reproduce**
1) Setup `OutgoingAudioOptions` with `muted = true`
2) Join call using `join(with:joinCallOptions:completionHandler:)` of `ACSCallAgent`
3) Set media diagnostics delegate of `call.feature(Features.localUserDiagnostics)`
4) Speak
5) Watch for `mediaDiagnostics(_: MediaDiagnostics, didChangeIsSpeakingWhileMicrophoneIsMuted args: DiagnosticFlagChangedEventArgs)` calls

***Code Snippet***
1.
```
let outgoingAudioOptions = OutgoingAudioOptions()
outgoingAudioOptions.muted = true
joinCallOptions.outgoingAudioOptions = outgoingAudioOptions
```
3.
```
let localUserDiagnostics = call.feature(Features.localUserDiagnostics)
let mediaDiagnostics = localUserDiagnostics.mediaDiagnostics
mediaDiagnostics.delegate = self
```

**Expected behavior**
After joining the call muted  the delegate method `mediaDiagnostics(_: MediaDiagnostics, didChangeIsSpeakingWhileMicrophoneIsMuted args: DiagnosticFlagChangedEventArgs)` should still be called

**Setup (please complete the following information):**
 - OS: iOS 17.2.1
 - IDE : Xcode 15.2
 - Version of the Library used: 'AzureCommunicationCalling' '2.8.0'

**Additional context**
When joining the call unmuted and then muting it, everything works fine.

**Comment by tjprescott** [comment] 2024-02-12 17:42
@raosanat can you please take a look?

**Comment by lucianopa-msft** [comment] 2024-02-20 18:09
Hey @alexvolchek,

This is expected behavior, as when you started the call with mute the application didn't request the access to microphone (you can note that there is no orange dot or mic signal](https://support.apple.com/en-us/108331#:~:text=With%20iOS%2014%20or%20later,an%20app%20on%20your%20iPhone.)) , so whenever the application doesn't have the hold of the mic from the OS, we can get the audio signal to tell if user speaking while muted. Once unmuted and muted again you can notice that the app now has orange dot which mean mic access so we can detect speaking while muted.

**Comment by raosanat** [comment] 2024-02-26 18:14
Closing the issue as its a limitation because of CallKit.

**Closed by raosanat** 2024-02-26 18:14 UTC
Labels: question, Communication, customer-reported
